version: "3.6"

services:
  app:
    build:
      context: .
      target: build
    volumes:
      - "./:/go/app"
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    command: realize start
    container_name: ${PROJECT:-}-app
    working_dir: "/go/app"
    links:
      - "mysql:mysql"
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=secret
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=example
      - REDIS_HOST=redis
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    tty: true

  mysql:
    image: mysql:8.0.15
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    container_name: ${PROJECT:-}-mysql
    hostname: mysql
    volumes:
      - "./storage/mysql:/var/lib/mysql"
      - "./configs/my.cnf:/etc/mysql/conf.d/my.cnf"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tty: true

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: ${PROJECT:-}-redis
    hostname: redis
    tty: true
